name: 'Continuous Delivery'

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  cloud-run-update:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: 'repository checkout'
      uses: 'actions/checkout@v4'

    - name: 'gcp auth'
      id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'gcloud setup'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'cloud run deploy'
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        project_id: '${{ env.GCP_PROJECT_ID }}'
        region: 'us-central1'
        service: 'mle-challenge'
        source: '.'
        revision_traffic: 'LATEST=100'
